apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: dockerjenkins444/mysecondrepo:1.0.0
          ports:
            - containerPort: 8080
# service type load balancer
---
apiVersion: apps/v1
kind: Service
metadata:
  name: server-demo-svc
spec:
  selector:
    app: web-svc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
